---
- hosts: webservers
  become: yes
  tasks:
  - name: install java in ubuntu
    apt:
     name: "{{javaonubuntu}}"
     state: present
    when: ansible_os_family == "Debian"

  - name: install java in redhat
    yum:
     name: "{{javaonredhat}}"
     state: present
    when: ansible_os_family == "RedHat"
 