---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: git tree wget install in ubuntu14
    apt:
     name: "{{ item }}"
     state: present
    with_items:
     - wget
     - tree
     - git

