---
- hosts: webservers
  become: yes
  tasks:
  - name: install webserver in ubuntu14
    apt: 
     name: "{{webserveronubuntu}}"
     state: present 
    when: ansible_os_family == "Debian" 

  - name: start webserver
    service:
     name: "{{webserveronubuntu}}"
     state: started
    when: ansible_os_family == "Debian" 

  - name: install webserver in redhat
    yum: 
     name: "{{webserveronredhat}}"
     state: present
    when: ansible_os_family == "RedHat" 

  - name: start webserver
    service:
     name: "{{webserveronredhat}}"
     state: started
    when: ansible_os_family == "RedHat" 