---
- hosts: all
  become: yes
  tasks:
  - name: install webserver in ubuntu14
    apt:
     name: apache2
     state: present

  - name: start webserver
    service:
     name: apache2
     state: started

